CFLAGS += -I/usr/local/include -fPIC -I/sw/include
LDFLAGS += -L/usr/local/lib -L/sw/lib -framework CoreAudio
DYLIBFLAGS += -dynamiclib

LIB_MADDEC := libmaddec.dylib
AUDIO_OBJS := audio_macosx_rb.o audio_macosx.o

include Makefile.common

$(LIB_MADDEC): $(LIB_MADDEC_OBJS)
	$(CC) $(LDFLAGS) $(DYLIBFLAGS) -o $@ \
              $(LIB_MADDEC_OBJS) -lm -lmad

